apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-agent.fullname" . }}
  labels: {{- include "hive-agent.labels" . | nindent 4 }}
data:
  HIVE_CLUSTER_NAME: {{ required "clusterName is required" .Values.clusterName | quote }}
  HIVE_API_ENDPOINT: {{ required "apiEndpoint is required" .Values.apiEndpoint | quote }}
  HIVE_PROVIDER: {{ required "provider is required" .Values.provider | quote }}
  HIVE_LOG_LEVEL: {{ .Values.logLevel | quote }}
  HIVE_LISTEN_ADDRESS: ":8080"
