apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hive-agent.fullname" . }}
  labels: {{- include "hive-agent.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hive-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress: []
  egress:
  - {}
