apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hive-agent.fullname" . }}
  labels: {{- include "hive-agent.labels" . | nindent 4 }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hive-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hive-agent.fullname" . }}
  labels: {{- include "hive-agent.labels" . | nindent 4 }}
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hive-agent.fullname" . }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
