apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive-agent.fullname" . }}
  labels: {{- include "hive-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  HIVE_API_KEY: {{ required "apiKey is required" .Values.apiKey | quote }}
